name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: ["386", "amd64"]
        exclude:
          - goos: darwin
            goarch: "386"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release code
        uses: likexian/go-release-action@v0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          BUILD_IN_DIR: cmd/cloudflare-internal-ip-ddns
          BUILD_BIN_DIR: bin
          BUILD_BIN_FILE: cloudflare-internal-ip-ddns
          BUILD_FLAGS: -v
          BUILD_LDFLAGS: -w -s
          PACK_ASSET_FILE: cloudflare-internal-ip-ddns-${{ matrix.goos }}-${{ matrix.goarch }}
          # PACK_INCLUDE_DIR: cloudflare-internal-ip-ddns
          # PACK_EXTRA_FILES: LICENSE README.md
      - name: Release version
        run: echo ${{ env.tag_name }}